CC=g++
CFLAGS=-m32 -g -Wno-write-strings

Example: Example.cpp
	$(CC) $(CFLAGS) -o Example Example.cpp ../SIB/SIBSchemas.cpp ../SIB/SIBStrings.cpp ../SIB/SIB.cpp ../ModRegRM/ModRegRMSchemas.cpp ../ModRegRM/ModRegRMStrings.cpp ../ModRegRM/ModRegRM.cpp ../Operand/OperandSchemas.cpp ../Operand/OperandStrings.cpp ../Operand/Operand.cpp ../Operator/OperatorSchemas.cpp ../Operator/OperatorStrings.cpp ../Operator/Operator.cpp ../Instruction/InstructionSchemas.cpp ../Instruction/Instruction.cpp ../Disassembler.cpp
